INSERT INTO ingredients (name, gi, source) VALUES
('palm oil', 0, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('vegetable oil', 0, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('olive oil', 0, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('bell pepper', 15, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('habanero', 15, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('scotch bonnet', 15, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('egusi seeds', 35, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('coconut milk', 40, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('ogbono', NULL, 'Not known per source - needs further research'),
('ugu leaf', NULL, 'Not known per source - needs further research'),
('oha leaf', NULL, 'Not known per source - needs further research'),
('bitterleaf', NULL, 'Not known per source - needs further research'),
('uziza leaf', NULL, 'Not known per source - needs further research'),
('utazi leaf', NULL, 'Not known per source - needs further research'),
('crayfish', 0, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('stockfish', 0, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('iru', NULL, 'Not known per source - needs further research'),
('tomato paste', 38, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('ogiri', NULL, 'Not known per source - needs further research'),
('basmati rice', 58, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('parboiled rice', 70, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('brown rice', 50, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('garri', 74, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('yam', 65, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('cassava', 55, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('taro yam', 48, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('tomato', 30, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('onion', 15, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('plantain', 40, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('fried plantain', 70, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('bouillon cube', 0, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('salt', 0, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('cayenne pepper', 15, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('dried prawn', 0, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('potato', 70, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('spinach', 15, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('sweet potato', 70, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('okra', 20, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('ewedu', 15, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('black-eyed beans', 33, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('honey beans', 40, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('green beans', 30, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('cocoyam', NULL, 'Not known per source - needs further research'),
('chicken', 0, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('goat', 0, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('beef', 0, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('lamb', 0, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('pork', 0, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('butter', 0, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('carrot', 30, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('egg', 0, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('ginger', 15, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('pasta', 50, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('rolled oats', 59, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('quick oats', 65, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('garlic', 30, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('all-purpose flour', 85, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('oat flour', 44, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('baking soda', 0, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('cumin', 15, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('white bread', 75, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('wheat bread', 70, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('bay leaves', 15, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('cashew nuts', 15, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('peanut', 15, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('kidney beans', 24, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('black beans', 30, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('spaghetti', 55, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('granulated sugar', 65, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('brown sugar', 64, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('sweetener (sugar substitute)', 0, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('corn', 48, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('broccoli', 15, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('akamu/ogi', 75, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('apple', 36, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('banana', 48, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('mango', 56, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('pineapple', 66, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('orange', 35, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('tangerine', 30, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('african star apple (agbalumo, udara)', NULL, 'Not known per source - needs further research'),
('broth/stock water', 0, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('ofada rice', 50, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('amala', 54, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('semovita', 65, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('pounded yam', 72, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('fufu', 94, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('sweet yogurt', 52, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('greek yogurt', 11, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('milk', 31, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('basil', 5, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('cauliflower', 15, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('celery', 15, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('chickpeas', 10, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('cucumber', 15, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('salmon', 0, 'glycemic-index.net / logifoodcoach.com / calorienaija.com'),
('tuna', 0, 'glycemic-index.net / logifoodcoach.com / calorienaija.com')
ON CONFLICT (name) DO NOTHING;